### ISSUE TITLE
Announcement mechanism

### ISSUE THREAD

**Issue by mwcw** [bcgit/pc-dart#116]
Hi,

How are dart project users normally notified of updates, releases etc?

For other projects we have it is a mailing list for announcements.

MW

**Comment by AKushWarrior** [comment]
I don't believe there's a standardized system; a mailing list sounds like a decent idea (though I don't know that we'd necessarily see a lot of traction).

**Comment by Ephenodrom** [comment]
Normally you would use something like the command line tool "dart pub outdated" (https://dart.dev/tools/pub/cmd/pub-outdated) to see if there are any new versions of packages used in your project. But there is still no mechanism to inform the user directly. Maybe this would be a good idea for a feature request to pub.dev (https://github.com/dart-lang/pub-dev).
