### ISSUE TITLE
Error when decrypting or encrypting unpadded AES-CTR

### ISSUE THREAD

**Issue by Sorunome** [bcgit/pc-dart#13]
When trying to decrypt or encrypt unpadded AES-CTR this library will throw an error, if the provided data isn't fully block-sized. The example given here uses the dart "encrypt" package, but I got told that it was an issue within pointycastle and that I should report it here:

```dart
import 'dart:typed_data';
import 'package:encrypt/encrypt.dart';

void main() {
  // these are all zero only to demonstrate the issue
  final key = Uint8List(32);
  final cipher = Uint8List(44); // just make sure that this isn't block-sized  
  final iv = Uint8List(16);
  final res = AES(Key(key), mode: AESMode.ctr, padding: null).decrypt(Encrypted(cipher), iv: IV(iv));
  print(res.toString());
}
```

The error is:

```
RangeError (index): Index out of range: index should be less than 44: 44
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2209:7)
#1      SICStreamCipher.processBytes (package:pointycastle/stream/sic.dart:61:39)
#2      StreamCipherAsBlockCipher.processBlock (package:pointycastle/adapters/stream_cipher_as_block_cipher.dart:31:18)
#3      AES._processBlocks (package:encrypt/src/algorithms/aes.dart:45:25)
#4      AES.decrypt (package:encrypt/src/algorithms/aes.dart:35:14)
#5      main (file:///home/sorunome/repos/famedly/famedlysdk/test.dart:9:63)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

As work-around you can manually 0-pad your input to be of full block-length and afterwards chop off those extra bytes again.

CTR (and CFB & OFB) are stream ciphers, rather than block ciphers. As such they don't require the input to be a specific blocksize. See @uhoreg 's comment here: https://github.com/leocavalcante/encrypt/issues/136

**Comment by AKushWarrior** [comment]
It's not a PointyCastle issue; this library exposes all the primitives you need to encrypt as a stream cipher. The library ALSO provides primitives to use these modes as block ciphers.

The author of that lib implemented CFB, OFB, and CTR using the block cipher version; see my comment in that issue.

**Comment by Sorunome** [comment]
Thanks a lot for the help!
