### ISSUE TITLE
[SECURITY] AES is Susceptible to Cache-Timing Attacks

### ISSUE THREAD

**Issue by soatok** [bcgit/pc-dart#141]
Source code:

* https://github.com/bcgit/pc-dart/blob/08d1aaa920e4d00ddf94140f65f952cac48707d1/lib/block/aes_fast.dart#L131-L219
* https://github.com/bcgit/pc-dart/blob/08d1aaa920e4d00ddf94140f65f952cac48707d1/lib/block/aes_fast.dart#L230-L317

The core problem here is the use of a table look-up, which leaks your AES keys through cache-timing.

Relevant papers:

* https://cr.yp.to/antiforgery/cachetiming-20050414.pdf
* https://www.microsoft.com/en-us/research/wp-content/uploads/2006/10/aes-timing.pdf

Mitigation: [Bitsliced S-Boxes](https://www.bearssl.org/constanttime.html#aes).

See also: **[Bitsliced AES Implementation in C](https://bearssl.org/gitweb/?p=BearSSL;a=blob;f=src/symcipher/aes_ct.c;h=66776d9e206c92cbbf3fa799c651a3d3652bd75a;hb=HEAD#l29)**

**Comment by AKushWarrior** [comment]
Okay, so this is a general issue with S-box based AES implementations; notably, the correspondent AES implementation from Bouncy Castle is deprecated with the notice that it [should not be used when close observation is possible](https://github.com/bcgit/bc-java/blob/9f95e5c710732bd8c703299b9d5ca1eea6f1317c/core/src/main/java/org/bouncycastle/crypto/engines/AESFastEngine.java#L33).

[This implementation](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/engines/AESEngine.java), currently the suggested general-use BouncyCastle implementation, adds operations to compute the other tables from one precomputed table, making a summative cache timing attack infeasible (at least, that's my understanding).

@mwcw do you have thoughts or a plan to resolve this?

**Comment by mwcw** [comment]
Hi,

I'll port AES engine over and get it tested and released ASAP.

MW

**Comment by mwcw** [comment]
The AESEngine from bc-java has been ported in as a replacement and version mentioned here replaced.

A release 3.4.0-rc1 has been created.

MW

**Comment by soatok** [comment]
Don't forget to fix #140 in the same go. (It's a smaller diff than porting a new engine from Java,, and is also important for the security of AES-GCM.)

**Comment by mwcw** [comment]
https://github.com/bcgit/pc-dart/releases/tag/v3.4.0
