### ISSUE TITLE
Write complete guide for usage (Documentation issue)

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#15]
This library has always had an issue with documentation. I figured that I might take a crack at the issue; my work is at https://akushwarrior2.gitbook.io/pointycastle-a-guide/.

Not especially notable or anything, but I figured there should be a place for you guys to track my progress.

**Comment by AKushWarrior** [comment]
that site I put together isn't an end-all be-all by any means. It's just a cohesive way of dealing with the documentation issue. The best thing to do would be to use dartdocs, but that will take a while, so we need a stand-in. (@mwcw dartdocs are like a Dart analogue for javadocs. They're automatically compiled and displayed in a [generated API reference](https://pub.dev/documentation/pointycastle/latest/).)

**Comment by Ephenodrom** [comment]
Some other ideas :
- Create a documentation page and host it via github pages. 
- write some articles at medium.com

**Comment by AKushWarrior** [comment]
>     * Create a documentation page and host it via github pages.
This is probably what we want to do, instead of hosting on some random third-party.

>     * write some articles at medium.com
Good idea!
