### ISSUE TITLE
Remove pointycastle from the front of every library's name

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#17]
To help with performance, each algorithm and cipher in this package is split into a separate "library". Each library name, for some reason, has pointycastle affixed to the front. This makes browsing the [API Reference](https://pub.dev/documentation/pointycastle/latest/) needlessly difficult.

Example: https://github.com/bcgit/pc-dart/blob/21569537015d7f1b1b6373499ab19fc4624c85f7/lib/stream/sic.dart#L3

**Comment by AKushWarrior** [comment]
In the given example, the new code would look like: 
```dart
library impl.stream_cipher.sic;
```

**Comment by mwcw** [comment]
Ok 

Lets look at it after I am finished with https://github.com/bcgit/pc-dart/pull/14

MW

**Comment by AKushWarrior** [comment]
Yup it should be an easy fix.

I can write a macro if that would help.

**Comment by AKushWarrior** [comment]
@mwcw Just realized you finished with #14. Do you want me to PR for this?

**Comment by mwcw** [comment]
Hi

Yes please I suspect it will be a big one.

We really appreciate your contributions to this api.

Thanks 

MW

**Comment by mwcw** [comment]
Hi,

I am going to do this now.

We should look at a release after this.

MW

**Comment by AKushWarrior** [comment]
Okay, I've been meaning to do this but never got around to it. If we're releasing, there's probably some housekeeping we should do on the README. I'll work on and commit that.

**Comment by mwcw** [comment]
Ok it is a significant commit.

The tests still pass and it should sync up shortly.

Let me know how you go and we can close the ticket if everything is fine.

MW
