### ISSUE TITLE
Separate KeccakDigest and SHA3Digest into 2 files

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#18]
In pointycastle, you can import each file individually, so it doesn't make sense to clump two separate algorithms in the same file.

That named constructor setup was because I didn't want to mess things up refactoring into 2 classes. Now that you guys have done that (thanks to @meganwoods and @mwcw), there's no reason to keep SHA-3 and Keccak together.

**Comment by mwcw** [comment]
Ok I have done this.

At the expense of sounding like a C++ / Java developer I struggled a bit with the lack a notion of protected fields. I ended up just making a copy and rolling the sha3 mods into one of them.

Let me know what you think and yes the two committers are both me.

MW
