### ISSUE TITLE
Incorrect api interface for PSSSigner

### ISSUE THREAD

**Issue by giregk** [bcgit/pc-dart#189]
I believe this PR should be merged: https://github.com/bcgit/pc-dart/pull/183

Indeed, the salt parameter is already included in a PSS signature output, so the code can find it by itself. The developer should not be required to deal with the salt manually.

**Comment by Ephenodrom** [comment]
The PR was merged, but I commited directly into the mirror git repository. With the latest pointycastle version it is now possible to verify a PSS signature with just the salt length.

If you still think there need to be some code changes, feel free to comment or open a new PR.

**Comment by giregk** [comment]
I must be missing something because I don't see the updated code in this repo and I don't see the pss_signer.dart file in the original repo.

**Comment by Ephenodrom** [comment]
@giregk 
Sorry that was my fault. I said that i commited the fix directly, but I didn't. Will release a new version next week with the fix.

**Comment by giregk** [comment]
@Ephenodrom amazing thank you !

**Comment by Ephenodrom** [comment]
Sorry that this took some time. Version 3.7.3 is now live on pub.dev including the fix.
