### ISSUE TITLE
Add GCM

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#19]
In steel_crypt, I pulled GCM from a fork of PointyCastle.

Here's the associated PR: https://github.com/PointyCastle/pointycastle/pull/153

**Comment by AKushWarrior** [comment]
I'll rebase + touch up this PR and notify when done.

**Comment by AKushWarrior** [comment]
@mwcw this is done and ready for merging in the linked PR.

**Comment by mwcw** [comment]
Thanks..

I have merged the PR.

MW
