### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by edwardmp** [bcgit/pc-dart#195]
Hi,

It would be good to ship a new release, given quite some stuff has been added but not released yet.

CC @Ephenodrom

**Comment by Ephenodrom** [comment]
Sounds good. Will try to get it done this week.

**Comment by edwardmp** [comment]
@Ephenodrom do you need any help?

**Comment by Ephenodrom** [comment]
@edwardmp 
Hello and sorry the late reply. This repository is currently out of sync with the origin repository. I ask the responsible person to sync it. Currently version 3.7.3 is available on pub.dev and should contain the newer stuff. Can you take a look and check which changes are missing ?

**Comment by edwardmp** [comment]
@Ephenodrom ah thanks for pointing that out. I wasn't aware this was not the origin repo. I will try out 3.7.3 but believe everything should be there!
