### ISSUE TITLE
Create x509 certificate

### ISSUE THREAD

**Issue by insinfo** [bcgit/pc-dart#196]
Hi, Is it possible, or are there any plans for creating X.509 certificates, CSR and KEY ?

**Comment by Ephenodrom** [comment]
Yes this is possible, but only on a low level. You have to create the ASN1 structure on your own. Another way is to use the Package "Basic Utils". It has the functionality to create X509 certificates and more and is based on the pointycastle project. You can use the package or check the code on how it is done.
