### ISSUE TITLE
Support dart2wasm

### ISSUE THREAD

**Issue by leecommamichael** [bcgit/pc-dart#221]
To reproduce:

- have the dart2wasm compiler
- import this package into a main.dart with void main
- run dart compile wasm main.dart
Output:

../../../AppData/Local/Pub/Cache/hosted/pub.dev/pointycastle-3.7.4/lib/src/platform_check/node_crypto.dart:5:1: Error: JS interop library 'package:js/js.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js.dart';
^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/pointycastle-3.7.4/lib/src/platform_check/web.dart:5:1: Error: JS interop library 'package:js/js.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js.dart';
^

This library impacts the popular `package:image`. I've filed a matching report with them [here](https://github.com/brendan-duncan/image/issues/610).

**Comment by The-RootCause** [comment]
Definitely needed since the package is used in many known packages making them unusable with Wasm. 
Thank you

**Comment by konsultaner** [comment]
I started porting my code to the web package to support wasm. It was quite hard to get into it, but finally got it. I might be able to help here.

I only saw 2 files where actual web code was written. Is that right? I could exchange the old `package:js` with `package:web`. That [`package:web`](https://github.com/dart-lang/web) is fully compatible with the dart2wasm compiler.

**Comment by Binozo** [comment]
@konsultaner could you please elaborate how you fixed that on your side?

I've replaced `import 'package:js/js.dart';` with `import 'package:web/web.dart';` in the following files: 
- `pointycastle-3.7.4/lib/src/platform_check/node_crypto.dart`
- `pointycastle-3.7.4/lib/src/platform_check/web.dart`

**Comment by konsultaner** [comment]
Dart fixed the blocking issue. If someone would take a look at my PR, this issue could be closed 😇

**Comment by konsultaner** [comment]
@leecommamichael this issue is fixed. You might want to close this issue.

**Comment by Ephenodrom** [comment]
Close as the PR is merged and live on pub.dev.

**Comment by sgehrman** [comment]
doesn't work, you are includeing teh js package.

[dart:js_interop](https://api.dart.dev/stable/dart-js_interop), which replaces package:js and dart:js

**Comment by konsultaner** [comment]
Where is it used? Im using pc-dart in my package and it compiles to wasm.
