### ISSUE TITLE
version 3.8.0 should depend dart 3.1.0 instead of 3.0.0

### ISSUE THREAD

**Issue by wanjm** [bcgit/pc-dart#230]
[dart:js_interop](https://api.dart.dev/stable/3.1.0/dart-js_interop/dart-js_interop-library.html)
[dart:js_interop_unsafe](https://api.dart.dev/stable/3.1.0/dart-js_interop_unsafe/dart-js_interop_unsafe-library.html)

is imported in 3.1.0, so version 3.8.0 should increase the minial SDK version;

**Comment by mosuem** [comment]
This is breaking the master branch of `package:grpc`, see https://github.com/mosuem/pc-dart/actions/runs/8686453387/job/23817981444.

**Comment by Ephenodrom** [comment]
@mosuem A new version 3.9.0 is available on pub.dev including this PR. Once the repository is synced this PR will be closed.

Thank you very much!

**Comment by wanjm** [comment]
and i think 3.8.0 should be removed. for I am use flutter 3.10 now;
flutter pub get will try to get 3.8.0. but is not supported;

**Comment by Ephenodrom** [comment]
3.8.0 can not be removed anymore. This issue is closed.
