### ISSUE TITLE
Non-nullable Migration

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#24]
Dart is migrating to Non-Nullable By Default. This should speed up PointyCastle significantly when it is compiled AOT, so we should begin migrating this library soon.

The feature is still in preview, so there's no hurry, but it's worth considering. We could use bc-kotlin as a model for the transition.

https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3

**Comment by mwcw** [comment]
Ok,

While it is good to be on the front foot, I think wait until the language feature is stable.

MW

**Comment by AKushWarrior** [comment]
> Ok,
> 
> While it is good to be on the front foot, I think wait until the language feature is stable.
> 
> MW
> 

Agreed.

**Comment by AKushWarrior** [comment]
@mwcw the null-safety feature is now in beta, and it's recommended for packages to create a prerelease branch which is ported to nullsafety. There has also been a promise of runtime performance improvements, since the language no longer has to perform null checks.

Associated reading:
Feature overview: https://dart.dev/null-safety
Migration guide: https://dart.dev/null-safety/migration-guide

This library is a "core" dependency, so any downstream packages/applications will end up needing this package migrated before they can do so. By starting the process now, we can "get ahead of the curve", so that this library is fully migrated when the feature reaches stable and production applications begin to migrate. It looks like the Dart team has built a migration tool, so this process should be mostly a careful inspection and correction on auto-migration.

**Comment by mwcw** [comment]
Hi,

Ok, I am trying to get back onto the dart project, we are heading towards towards a new round of FIPS certifications and it is consuming all of my time at the moment, although the end is in sight.

I will try and take a look at those links in the next day (Melbourne AU).

MW

**Comment by acoutts** [comment]
@AKushWarrior @mwcw please migrate this with a pre-release like other packages have done. All packages that consume this package cannot migrate until this one is migrated, so all downstream packages are blocked until you set out a nullsafety pre-release as outlined in the migration guide: https://dart.dev/null-safety/migration-guide

**Comment by AKushWarrior** [comment]
@mwcw looks like there's been some organic roadblocks. It'll take a while, but we should definitely start the process.

**Comment by acoutts** [comment]
You can see here that there are currently 108 packages which depend on `pointycastle` on pub.dev, so all of them are in the same blocked state: https://pub.dev/packages?q=dependency%3Apointycastle

**Comment by AKushWarrior** [comment]
It's also worth noting that pointycastle is one of the most used packages on pub. This is both because of downstream package dependencies and direct users. I think that this is high-urgency given how much code we'd have to port, but this library doesn't use null extensively (so the port should be okay).

**Comment by AKushWarrior** [comment]
Working on this on my fork. Will update with more details as I have them. You can view progress at https://github.com/AKushWarrior/pc-dart

@mwcw to avoid merge conflicts, could you not merge PRs into this repository for a few days? I want to make sure that my fork is fast-forward-safe with this one.

**Comment by mwcw** [comment]
Hi,

Yep I can do that, did you by chance see an email from me?

MW

**Comment by AKushWarrior** [comment]
Haven't seen one. What address did you send it to?

Typically I use akushwarrior@gmail.com for open source stuff.

**Comment by mwcw** [comment]
Hi, 

I have send you another email, I am not sure what happened.

MW

**Comment by AKushWarrior** [comment]
It looks like the majority of tests are passing on my fork. It's at 435 passing, 16 failing currently. I think that this should be ready for prerelease by the end of tomorrow, assuming all goes well.

**Comment by mwcw** [comment]
Sure let me know!

Given the size of the change I think it should go out as 2.1.0

MW

**Comment by AKushWarrior** [comment]
> Sure let me know!
> 
> Given the size of the change I think it should go out as 2.1.0
> 
> MW

It should be in the form "2.1.0-null-safety" or something of that sort. The dart docs specify; I'll get it set up before I finalize the PR.

**Comment by AKushWarrior** [comment]
@mwcw this is taking a really long time. Not sure where these last couple errors are coming from. Going to do some diffs with the old code today and see if that helps.

**Comment by AKushWarrior** [comment]
@mwcw @acoutts The migration is finished and the PR is filed. I've taken great care to ensure that the package is publish-ready; all the logistical problems, dependency management, versioning, etc. has been taken care of along with the migration itself.

I declared this version to be 3.0.0 because of this guideline: https://dart.dev/null-safety/migration-guide#package-version. That versioning bump makes sense to me because this is fundamentally a breaking change for downstream users, in that their code would have to be migrated to use this package. That they would have migrated anyways is immaterial to semantic versioning :)
