### ISSUE TITLE
Support RSA-PSS

### ISSUE THREAD

**Issue by CDDelta** [bcgit/pc-dart#34]
It would be great if this package had RSA-PSS support. It has been requested before [here](https://github.com/PointyCastle/pointycastle/issues/58).

I can try and work on implementing it if the team doesn't have the bandwidth to do so or is uninterested but I'm not at all familiar with cryptography so will need some guidance on how to do it.

Is porting the C# and Java implementation "simply" a matter of changing the syntax? 😅

**Comment by AKushWarrior** [comment]
It is USUALLY a matter of changing the syntax, but it can get tricky if you don't have any idea of what's going on under the hood.

You can definitely try it. Make sure you also port the tests from bouncycastle to the tests folder.

**Comment by CDDelta** [comment]
Alright, I'll give it a go sometime next week. Thank you!
