### ISSUE TITLE
Store public exponent in RSAPrivateKey

### ISSUE THREAD

**Issue by gnawf** [bcgit/pc-dart#45]
So I've noticed that `RSAPrivateKey` doesn't store the public exponent. This would very useful for encoding private keys in PKCS1 format – which requires the public exponent.

From what I can tell, the `bc-java` library stores the public exponent – [see](https://github.com/bcgit/bc-java/blob/2b976f5364cfdbc37d3086019d93483c983eb80b/core/src/main/java/org/bouncycastle/crypto/params/RSAPrivateCrtKeyParameters.java#L20-L21).

---

Furthermore, I was reading [this blog post](https://medium.com/flutter-community/asymmetric-key-generation-in-flutter-ad2b912f3309) and noticed it incorrectly uses the private exponent as the public exponent when encoding the private key. I believe that the `d` and `e` alias properties in the private and public key classes are bad design as they introduce confusion. The `bc-java` library exposes these properties in their longer form `getExponent` and `getPublicExponent` and doesn't offer any shortened names or aliases.

I suggest deprecating the `d` and `e` properties (eventually removing them), and adding a `publicExponent` to the private key class.

**Comment by mwcw** [comment]
This has been fixed.

Thanks for the report.

**Comment by gnawf** [comment]
@mwcw thanks for the change. Just got around to checking it.

Any reason why there's a `pubExponent` AND a `publicExponent`?

```dart
   BigInt get publicExponent => pubExponent;
```

FWIW: you can always change a field to a getter. See this [linter rule](https://dart-lang.github.io/linter/lints/unnecessary_getters_setters.html).

> AVOID wrapping fields in getters and setters just to be "safe".
> 
> In Java and C#, it's common to hide all fields behind getters and setters (or properties in C#), even if the implementation just forwards to the field. That way, if you ever need to do more work in those members, you can without needing to touch the callsites. This is because calling a getter method is different than accessing a field in Java, and accessing a property isn't binary-compatible with accessing a raw field in C#.
> 
> Dart doesn't have this limitation. Fields and getters/setters are completely indistinguishable. You can expose a field in a class and later wrap it in a getter and setter without having to touch any code that uses that field.

So I think pubExponent should be removed and the constructor changed to:

```dart
  // The secret prime factors of n
  final BigInt p;
  final BigInt q;
  final BigInt publicExponent;

  /// Create an RSA private key for the given parameters.
  RSAPrivateKey(BigInt modulus, BigInt privateExponent, this.p, this.q,
      [this.publicExponent])
      : super(modulus, privateExponent);
```
