### ISSUE TITLE
2.0.0-rc1 Release thread

### ISSUE THREAD

**Issue by mwcw** [bcgit/pc-dart#46]
Hi,

Release Candidate 1 of Pointy Castle 2.0.0 has been release.

Please try it out.

I would like to move through the rc phase reasonable quickly so we can get the 2.0.0 release out and move forward from there.

https://pub.dev/packages/pointycastle/versions/2.0.0-rc1

MW

**Comment by penhorwood** [comment]
Thanks!!!!

**Comment by AKushWarrior** [comment]
Awesome. Thanks for doing this. I'll do some publicity work on Reddit and Medium at some point to make people aware of the change...

**Comment by Ephenodrom** [comment]
I opened an issue (#47) with some improvements and small bugs I found while trying to use the pointycastle ASN1 lib instead of the current ASN1 lib within my basic utils package.

Will try to create a PR this or next week so we can add this to RC2 or to version 2.0.1.

**Comment by mwcw** [comment]
Hi,

@Ephenodrom I have no argument with having this sit as RC 1 until you are ready and then do a quick RC2.

MW

**Comment by mwcw** [comment]
RC 2 has been released, please see:  #49
