### ISSUE TITLE
Improve ASN1 Lib

### ISSUE THREAD

**Issue by Ephenodrom** [bcgit/pc-dart#47]
After changing to the RC1 (#46) I found some bugs and things to improve : 

- Add ASN1TeletextString to be compatible with the current ASN1Lib package
- Add ASN1GeneralizedTime to be compatible with the current ASN1Lib package
- Add add() method to the ASN1Sequence to be compatible with the current ASN1Lib package
- Add short version of some object identifiers like CN for common name.
- The encoding from ASN1Integer(BigInt.from(0)) differs from the current ASN1Lib package and is maybe buggy
- ASN1BitString can not handle "unused bits" this is a problem by parsing some X509 where the public key is stored in a BitString with beginning 00. Example PEM : 
```
-----BEGIN CERTIFICATE-----
MIIFDTCCA/WgAwIBAgIQBxYr+XmB67PWzCkR7C39iDANBgkqhkiG9w0BAQsFADBA
MQswCQYDVQQGEwJVUzERMA8GA1UEChMIT0VNIFRlc3QxHjAcBgNVBAMTFUZ1bGwg
T0VNIFRlc3QgUlNBIFN1YjAeFw0xOTAzMTEwMDAwMDBaFw0yMDAzMTAxMjAwMDBa
MHsxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIEwZCYXllcm4xEzARBgNVBAcTClJlZ2Vu
c2J1cmcxFzAVBgNVBAoTDkludGVyTmV0WCBHbWJIMRQwEgYDVQQLEwtFbnR3aWNr
bHVuZzEXMBUGA1UEAxMOanVua2RyYWdvbnMuZGUwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDDGv7+2oQyRWvFAt7UxtAQJB6zajegzrlvLLZ4+PhhJt6w
aSDW6IPV7H4uIvgL3cHP68AkATl+2fW0CEPy2i3vO27VDtxMp2oTk/IdPtVbNtZB
sjeFiNVzr7ZaD6z0u41WLEQbR34CmlWbggza3SS0tvPXD02YJpDz/Qm43hz0m+SJ
0IaesAM7b1tTbmlCxg3rm+CViU9wTsI9eUvOCZIjKS3E3MVcRJZTCCaZMp8JMKct
Ae4B90RunGbpvsYvWo4W4UQMFCVYcZp47FFeWcUnqx03nrSdP3LEEPcePVsRxPeB
ptsZzby9Wf7Sc2UNzTZSGjzxlpItgXdsjL4HiR/VAgMBAAGjggHGMIIBwjAfBgNV
HSMEGDAWgBS8odGV3/ZO7g4f11MzIg9X66vlUjAdBgNVHQ4EFgQUTriCU/8x5yQN
BoQPPYQcUVL7FUIwQQYDVR0RBDowOIIOanVua2RyYWdvbnMuZGWCEnd3dy5qdW5r
ZHJhZ29ucy5kZYISYXBpLmp1bmtkcmFnb25zLmRlMA4GA1UdDwEB/wQEAwIFoDAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwPgYDVR0fBDcwNTAzoDGgL4Yt
aHR0cDovL2NkcC5yYXBpZHNzbC5jb20vRnVsbE9FTVRlc3RSU0FTdWIuY3JsMEwG
A1UdIARFMEMwNwYJYIZIAYb9bAEBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3
LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQICMHUGCCsGAQUFBwEBBGkwZzAmBggr
BgEFBQcwAYYaaHR0cDovL3N0YXR1cy5yYXBpZHNzbC5jb20wPQYIKwYBBQUHMAKG
MWh0dHA6Ly9jYWNlcnRzLnJhcGlkc3NsLmNvbS9GdWxsT0VNVGVzdFJTQVN1Yi5j
cnQwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAwCJAiSMJSYCIrJZdcLmY
zgH/Hd6VUDQzuo/s8Q+UoqpwyPwGnmNpovvzfjtz2+bF0dCQwUWerm61kYF/3IU6
ucrdTW4uS+T11tipJgDUBU8jEHvASe+QNIP7BiNoXCs10SfI8FQajL0HxnHY0vKC
AAQiFStLngxNYduyz4C3ZUjeNjt/8NhCUhd2GZGA6gveHKvck47ZWFbblecH8Odw
nhzR+ztf+lSGoyQW+egNlPog/OLjr//kKx7kjuuvXa5Os8oPLENu6LAjTZJqGvJP
ga7IcCj2gCeuTdS4Ibhx3hiew7cfuGa9XbVd5JJmV8kIoFlzLrZpKB4eVDKqaNWg
/g==
-----END CERTIFICATE-----
```

**Comment by gnawf** [comment]
I found it very odd how `encodedBytes` is exposed. From what I can see it's the memoized result from `encode()`. It seems like it should be a private implementation detail?

Also throws off people switching from the ASN1Lib package, since their `encodedBytes` should be changed to `encode()`.

**Comment by Ephenodrom** [comment]
@mwcw @gnawf 
I created a PR to fix the above mentioned things.

**Comment by awhitford** [comment]
Related to https://github.com/Ephenodrom/Dart-Basic-Utils/issues/31...

⚠️ I will admit that I am not very familiar with ASN1.  The following comments are based on feedback from an exercise I went through in attempting to migrate `asn1lib` code to `pointycastle`. 

Consider the following:
https://github.com/bcgit/pc-dart/blob/e5cd4dd87d3a2b2f317b9a59b245978d92e965ee/lib/asn1/primitives/asn1_bit_string.dart#L31-L36

Is `tag` really something that would/could/should be changed?  Why not hard-code it like:
```dart
   ASN1BitString( 
       {this.stringValues, this.elements}) 
       : super(tag: ASN1Tags.BIT_STRING); 
```
?

Migrating from `asn1lib1` requires specifying the named parameter, which seems excessive for most use-cases.  And does it really make sense to potentially have `stringValues` _and_ `elements`?  Maybe multiple constructors or factory methods to handle different use-cases makes more sense?  Like:

```dart
    ASN1BitString(this.stringValues) : super(tag: ASN1Tags.BIT_STRING);
  
    ASN1BitString.fromElements(this.elements) : super(tag: ASN1Tags.BIT_STRING); 
```
?

**Comment by Ephenodrom** [comment]
Improvements are already merged. Complaints cannot be traced, because the effort for a change is limited.
