### ISSUE TITLE
ASN1BitString NPE bug

### ISSUE THREAD

**Issue by awhitford** [bcgit/pc-dart#50]
https://github.com/bcgit/pc-dart/blob/e5cd4dd87d3a2b2f317b9a59b245978d92e965ee/lib/asn1/primitives/asn1_bit_string.dart#L88-L90

This looks like a _Null Pointer Exception_ bug.  I just noticed it while investigating something else.

**Comment by Ephenodrom** [comment]
Will create a PR the next days.

**Comment by Ephenodrom** [comment]
@mwcw 
This can be closed now, due to the corresponding PR is closed.
