### ISSUE TITLE
ASN1Integer wrong encode

### ISSUE THREAD

**Issue by ertong** [bcgit/pc-dart#56]
`print(base64.encode(ASN1Integer(BigInt.from(128)).encode()));`
returns  AgGA  (020180)
expected  AgIAgA== (02020080) (verified by other implementations)

It looks like it is something related to signed/unsigned representation.

pointycastle: 2.0.0

**Comment by schancel** [comment]
Running into the same issue. When the BigInt is a positive but the encoded first byte would have 0x80, it doesn't end up padded.

**Comment by mwcw** [comment]
https://github.com/bcgit/pc-dart/pull/59
