### ISSUE TITLE
AES GCM Decrypt data with passphrase

### ISSUE THREAD

**Issue by redDwarf03** [bcgit/pc-dart#63]
Hello

have you an equivalence with js code (bold section)
the need is to decrypt an Encrypted data (String) with a passphrase (String)

export function decryptPrivateKey(data, passphrase) {
  const key = sha3.sha3_256.array(passphrase)
  const dataArray = Buffer.from(
    typeof data === 'string' ? hexToUint8Array(data) : new Uint8Array(data)
  )
  **const decipher = crypto.createDecipheriv(
    'aes-256-gcm',
    key,
    dataArray.slice(0, 12)
  )
  decipher.setAuthTag(dataArray.slice(dataArray.length - 16))
  const decrypted = [
    ...decipher.update(dataArray.slice(12, dataArray.length - 16)),
    ...decipher.final(),
  ]**
  return toHexString(decrypted)
}

**Comment by redDwarf03** [comment]
resolved.

**Comment by nambv** [comment]
hi @redDwarf03 can you share me the code that you resolved this issue? I am stucking on this. Thank you

**Comment by redDwarf03** [comment]
hi @nambv 
I didn't use PointyCastle finally...

I used ```https://pub.dev/packages/crypto_keys```

here is my code
```

// Dart imports:
import 'dart:convert';
import 'dart:typed_data';

// Package imports:
import 'package:crypto_keys/crypto_keys.dart' as cryptoKeys;
import 'package:hex/hex.dart';
import 'package:sha3/sha3.dart';

 Future<String> encryptedPrivateKeyToSeed(
      String encPrivateKey, String password) async {
    try {
      if (encPrivateKey.isEmpty || password.isEmpty) {
        return "";
      }

      var k = SHA3(256, SHA3_PADDING, 256);
      k.update(utf8.encode(password));
      final key = Uint8List.fromList(k.digest());
      var dataArray = Uint8List.fromList(HEX.decode(encPrivateKey));
      if (dataArray.length < 12) {
        return "";
      }
      final dataArray0to12 = dataArray.sublist(0, 12);
      final cypherText = dataArray.sublist(12);
      final iv = dataArray0to12;
      
      cryptoKeys.KeyPair keyPair = cryptoKeys.KeyPair.symmetric(
          cryptoKeys.SymmetricKey(keyValue: Uint8List.fromList(key)));

      cryptoKeys.Encrypter encrypter = keyPair.privateKey
          .createEncrypter(cryptoKeys.algorithms.encryption.aes.gcm);
      Uint8List decrypted = encrypter.decrypt(
          cryptoKeys.EncryptionResult(cypherText, initializationVector: iv));

      return HEX.encode(decrypted);
    } catch (e) {
      return "";
    }
  }
```

**Comment by nambv** [comment]
Thanks a lot @redDwarf03 !!! I will try it 👍

**Comment by nambv** [comment]
> hi @nambv I didn't use PointyCastle finally...
> 
> I used `https://pub.dev/packages/crypto_keys`
> 
> here is my code
> 
> ```
> 
> // Dart imports:
> import 'dart:convert';
> import 'dart:typed_data';
> 
> // Package imports:
> import 'package:crypto_keys/crypto_keys.dart' as cryptoKeys;
> import 'package:hex/hex.dart';
> import 'package:sha3/sha3.dart';
> 
>  Future<String> encryptedPrivateKeyToSeed(
>       String encPrivateKey, String password) async {
>     try {
>       if (encPrivateKey.isEmpty || password.isEmpty) {
>         return "";
>       }
> 
>       var k = SHA3(256, SHA3_PADDING, 256);
>       k.update(utf8.encode(password));
>       final key = Uint8List.fromList(k.digest());
>       var dataArray = Uint8List.fromList(HEX.decode(encPrivateKey));
>       if (dataArray.length < 12) {
>         return "";
>       }
>       final dataArray0to12 = dataArray.sublist(0, 12);
>       final cypherText = dataArray.sublist(12);
>       final iv = dataArray0to12;
>       
>       cryptoKeys.KeyPair keyPair = cryptoKeys.KeyPair.symmetric(
>           cryptoKeys.SymmetricKey(keyValue: Uint8List.fromList(key)));
> 
>       cryptoKeys.Encrypter encrypter = keyPair.privateKey
>           .createEncrypter(cryptoKeys.algorithms.encryption.aes.gcm);
>       Uint8List decrypted = encrypter.decrypt(
>           cryptoKeys.EncryptionResult(cypherText, initializationVector: iv));
> 
>       return HEX.encode(decrypted);
>     } catch (e) {
>       return "";
>     }
>   }
> ```

Thanks a lot @redDwarf03 ! It's totally worked 🚀 !!!! I appreciated
