### ISSUE TITLE
AES CCM mode

### ISSUE THREAD

**Issue by mneber** [bcgit/pc-dart#64]
Sorry I should have posted this here not the pre fold repo. 

Is there any plan to add CCM mode in the near future?

128 bit AES CCM is very common for Bluetooth. I need it for a project that I'm on now and can't find any dart plugin.

**Comment by AKushWarrior** [comment]
This project is heavily dependent on user pull requests. The original implementation (in BouncyCastle) is here: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/modes/CCMBlockCipher.java

If people need this, please upvote the original post in this issue (at least) or implement it yourself (if you can).

**Comment by AKushWarrior** [comment]
If there's a significant need for it, I can take some time and port it. I might not have time for a month or so, though.

**Comment by AKushWarrior** [comment]
@mneber done. It's included in #77. You can add my fork of this repository as a git dependency if you need it urgently.

**Comment by AKushWarrior** [comment]
This was released in the latest update, which is labeled 3.0.0-nullsafety.2 on https://pub.dev and has code in a branch of this repository. As of right now, the algorithm is only available in the null-safe version of this library, but you can trivially port it to non-null-safety. @mwcw you can close this.
