### ISSUE TITLE
Archival of original PointyCastle repo

### ISSUE THREAD

**Issue by izaera** [bcgit/pc-dart#67]
Hi there:

Just wanted to notify you that I have archived https://github.com/PointyCastle/pointycastle . It was still open for modification and people were still sending PRs and opening issues.

I redirected all of them here, but archiving the repo and writing a message in its README should do the trick much better.

I tried to contact @stevenroose to confirm that I could archive the repo but I haven't got any answer from him yet, so I decided to do it anyway after creating an issue to notify all subscribers and haven't received any comment from anybody in a week or so.

**Comment by stevenroose** [comment]
Hmm, I suspect you tried to contact my Gmail address instead of my new e-mail. I am desperately lost keeping track of that e-mail account. I'm ok with the archival. And I apologize for all the trouble my slow reactions have caused.

**Comment by izaera** [comment]
Nothing to apologize for :raised_hands: . Just wanted to make sure I wasn't breaking anything.

Regarding your e-mail, I didn't use it. I just mentioned you here in GH :-)
