### ISSUE TITLE
CHANGELOG title for 2.0.0-rc1

### ISSUE THREAD

**Issue by awhitford** [bcgit/pc-dart#68]
Minor issue with [CHANGELOG.md](https://github.com/bcgit/pc-dart/blob/master/CHANGELOG.md#version-200-rc1-2020-09-11-dart-sdk-version-211q):

```
#### Version 2.0.0-rc1 (2020-09-11) (Dart SDK version 2.1.1)::q!
```

See that `:q!` at the end?  Looks like a `vi` fail.

**Comment by redDwarf03** [comment]
Fixed. Available in the new version
