### ISSUE TITLE
Release 2.0.1

### ISSUE THREAD

**Issue by Ephenodrom** [bcgit/pc-dart#71]
Hello @mwcw 

Can you please create a new release on pub.dev ? Recently, there have been a few PRs that have been closed.

Regards

**Comment by AKushWarrior** [comment]
Second. The dart:io thing is still blocking usage on web.

**Comment by Ephenodrom** [comment]
@AKushWarrior This should be Dome with the closet PR #62

**Comment by AKushWarrior** [comment]
@Ephenodrom It was merged into the repo, but not published on pub.dev, which is my point. Users from pub.dev cannot currently access this library on web.

**Comment by Ephenodrom** [comment]
@mwcw Any timeline for this?

**Comment by mwcw** [comment]
I'll do it now.

MW

**Comment by mwcw** [comment]
Done
