### ISSUE TITLE
Add CONTRIBUTING.MD

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#72]
Given how much non-owners have contributed to this library, I think it's useful to provide a scaffold for contributions to this library. Notably, thus far, AES-GCM, ChaCha20, HKDF, Poly1305, ASN1, and Keccak/SHA-3 separation have all been recently contributed by people who were not maintainers of the project. Regularizing contributions to the library thus has significant value.

As for what it would include, I imagine it to be a sort of guide: we could have instructions for porting from BouncyCastle, instructions for tests, etc. I have a lot of experience with some of the issues that we run into porting from java (most notably, the lack of different integer sizes). The internal APIs in PointyCastle also differ somewhat significantly from those in Bouncy Castle.

**Comment by mwcw** [comment]
Yes,

I think it is a very good idea.

MW
