### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by moazelshebly** [bcgit/pc-dart#78]
It would be great if this package is migrated to support null safety changes.

Are there any plans for this to be implemented soon?

**Comment by AKushWarrior** [comment]
There's already an issue (#24) and PR (#77) it's should come out in the next couple weeks.

**Comment by AKushWarrior** [comment]
It's released as 3.0.0-nullsafety.2 on https://pub.dev and as a branch of this repository. @mwcw you can close this.
