### ISSUE TITLE
Generating X.509 certificates

### ISSUE THREAD

**Issue by KingDoxik** [bcgit/pc-dart#82]
Hi, I am trying to generate X.509 certificates. Is it possible with Pointy Castle? I found a 4 years old open issue in old Pointy Castle repo. Bouncy Castle has this feature. Thanks

**Comment by AKushWarrior** [comment]
Not possible as of now. I'm working on some randomness generators right now, but I'll take a look after I finish.

**Comment by Cobinja** [comment]
Is there any news on this?
