### ISSUE TITLE
PointyCastle analogous code for BouncyCastle Algorithm EC, curve Curve25519 key pair generation

### ISSUE THREAD

**Issue by hamirshekhawat** [bcgit/pc-dart#83]
Can I write Dart code for the following java file? https://github.com/gsasikumar/forwardsecrecy/blob/master/src/main/java/io/yaazhi/forwardsecrecy/service/ECCService.java
The file has methods to generate ec key pair using curve 25519. The public key is uncompressed. 
Does PointyCastle supports this?

**Comment by brandsimon** [comment]
@hamirshekhawat 
I am also interested in using ed25519. Have you made in progress with this?

**Comment by Ephenodrom** [comment]
#187
