### ISSUE TITLE
Merge null safety into master

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#85]
Null safety has been taken out of beta: https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

That means the null safety branch should be merged into master, and probably that we should update the version bounds.

I'll look into the latter; @mwcw, if you could do the former, that would be great.

**Comment by jonasroussel** [comment]
Any idea when it will be merged ?

**Comment by AKushWarrior** [comment]
Not sure, really depends on when Megan has a minute. You can already use it and the branch is largely stable.

**Comment by AKushWarrior** [comment]
This is done as of yesterday.
