### ISSUE TITLE
Enable CI for pull requests

### ISSUE THREAD

**Issue by AKushWarrior** [bcgit/pc-dart#9]
There should be a CI that runs tests and https://pub.dev/packages/pana on all PRs. This would allow you to evaluate the contribution of any given package.

**Comment by mwcw** [comment]
Ok

I have added travis ci and included pana in the build steps.

Let me know what you think?

I'll close this for now.

MW

**Comment by mwcw** [comment]
Stop the press...

Actually I have just looked at the example workflow.

MW

**Comment by AKushWarrior** [comment]
Agghhhh... I can't view CI on mobile.

I'll take a look when I'm back on my computer.

**Comment by AKushWarrior** [comment]
okay I just took a look. I basically did the same thing through GitHub actions instead of Travis; what you have now should work fine...
